version: '3.8'

services:

  db:
    environment:
      - ENVIRONMENT=production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    environment:
      - ENVIRONMENT=production
    networks:
      - backend_network

  frontend:
    environment:
      - ENVIRONMENT=production
    networks:
      - frontend_network
    ports:
      - "${REACT_HOSTPORT}:${REACT_PORT}"

  nginx:
    environment:
      - ENVIRONMENT=production
    ports:
      - "${NGINX_HOSTPORT}:80"
    volumes:
      - ./nginx:/etc/nginx/
    networks:
      - frontend_network
      - backend_network

volumes:
  postgres_data:
    driver: local

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

