version: '3.8'

services:

  db:
    environment:
      - ENVIRONMENT=production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network

  backend:
    environment:
      - ENVIRONMENT=production
    networks:
      - database_network
      - frontend_network

  frontend:
    environment:
      - ENVIRONMENT=production
    networks:
      - frontend_network
    ports:
      - "${REACT_HOSTPORT}:${REACT_PORT}"

  nginx:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    environment:
      - ENVIRONMENT=production
    volumes:
      - "${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf"
      # we may mount static asssets here in the future
    networks:
      - database_network
      - frontend_network

volumes:
  postgres_data:
    driver: local

networks:
  database_network:
    driver: bridge
  frontend_network:
    driver: bridge

